version: '3'

services:
  de-final-prj-local:
    build:
      context: ./src
    image: src:local
    ports:
      - 8998:8998 
      - 8280:8280
      - 15432:5432
    volumes:
      - "./src/dags:/lessons/dags:ro"  